-- Create Policies Table
create table if not exists policies (
  id uuid default gen_random_uuid() primary key,
  slug text unique not null,
  title text not null,
  content text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Enable RLS
alter table policies enable row level security;

-- Policies
create policy "Enable read access for all users"
on policies for select
to public
using (true);

create policy "Enable write access for admins"
on policies for all
to authenticated
using (true)
with check (true);

-- Insert initial data
INSERT INTO policies (slug, title, content)
VALUES
(
  'privacy-policy',
  'Privacy Policy',
  '<p>Grahasthee ("we", "us", or "our") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, and safeguard your information when you visit our website.</p><h5 class="mt-4 fw-bold text-uppercase">Information We Collect</h5><p>We collect information that you provided directly to us when you:</p><ul><li>Create an account or place an order.</li><li>Sign up for our newsletter.</li><li>Contact our customer support.</li></ul><p>This may include your name, email address, phone number, shipping address, and payment details.</p><h5 class="mt-4 fw-bold text-uppercase">How We Use Your Information</h5><p>We use the collected information to:</p><ul><li>Process and fulfill your orders.</li><li>Communicate with you about your orders and promotional offers.</li><li>Improve our website and customer service.</li><li>Prevent fraudulent transactions and enhance security.</li></ul><h5 class="mt-4 fw-bold text-uppercase">Cookies</h5><p>We use cookies to enhance your browsing experience. Cookies are small files stored on your device that help us understand your preferences and provide a personalized experience. You can choose to disable cookies through your browser settings, but it may affect some features of our website.</p><h5 class="mt-4 fw-bold text-uppercase">Third-Party Disclosure</h5><p>We do not sell, trade, or otherwise transfer your personally identifiable information to outside parties except for trusted third parties who assist us in operating our website, conducting our business, or servicing you (e.g., shipping partners, payment gateways), so long as those parties agree to keep this information confidential.</p><h5 class="mt-4 fw-bold text-uppercase">Data Security</h5><p>We implement a variety of security measures to maintain the safety of your personal information. Your sensitive information (like credit card data) is encrypted and transmitted via Secure Socket Layer (SSL) technology.</p><h5 class="mt-4 fw-bold text-uppercase">Your Consent</h5><p>By using our site, you consent to our website''s privacy policy.</p><h5 class="mt-4 fw-bold text-uppercase">Contact Us</h5><p>If there are any questions regarding this privacy policy, you may contact us at <a href="mailto:grahasthee@gmail.com">grahasthee@gmail.com</a></p>'
),
(
  'terms-of-service',
  'Terms of Service',
  '<p>Welcome to Grahasthee. These terms and conditions outline the rules and regulations for the use of Grahasthee''s Website.</p><h5 class="mt-4 fw-bold text-uppercase">1. Terms</h5><p>By accessing this website, we assume you accept these terms and conditions in full. Do not continue to use Grahasthee''s website if you do not accept all of the terms and conditions stated on this page.</p><h5 class="mt-4 fw-bold text-uppercase">2. Products & Services</h5><p>We make every effort to display as accurately as possible the colors and images of our products that appear at the store. We cannot guarantee that your computer monitor''s display of any color will be accurate.</p><p>We reserve the right to limit the sales of our products or services to any person, geographic region, or jurisdiction. We may exercise this right on a case-by-case basis.</p><h5 class="mt-4 fw-bold text-uppercase">3. Pricing & Payments</h5><p>Prices for our products are subject to change without notice. We reserve the right at any time to modify or discontinue the Service without notice at any time.</p><p>Payments must be made through our authorized payment gateways or via Cash on Delivery where applicable.</p><h5 class="mt-4 fw-bold text-uppercase">4. Shipping & Delivery</h5><p>Shipping and delivery are governed by our Shipping Policy. Delivery times are estimates and not guarantees.</p><h5 class="mt-4 fw-bold text-uppercase">5. Returns & Refunds</h5><p>Returns and refunds are governed by our Refund Policy. Please review it carefully before making a purchase.</p><h5 class="mt-4 fw-bold text-uppercase">6. User Comments & Feedback</h5><p>If you send certain specific submissions or creative ideas, suggestions, proposals, plans, or other materials, whether online, by email, or otherwise, you agree that we may, at any time, without restriction, edit, copy, publish, distribute and otherwise use in any medium any comments that you forward to us.</p><h5 class="mt-4 fw-bold text-uppercase">7. Prohibited Uses</h5><p>In addition to other prohibitions as set forth in the Terms of Service, you are prohibited from using the site or its content for any unlawful purpose, to solicit others to perform or participate in any unlawful acts, or to violate any international or local regulations.</p><h5 class="mt-4 fw-bold text-uppercase">8. Governing Law</h5><p>These Terms of Service and any separate agreements whereby we provide you Services shall be governed by and construed in accordance with the laws of India.</p><h5 class="mt-4 fw-bold text-uppercase">9. Contact Information</h5><p>Questions about the Terms of Service should be sent to us at <a href="mailto:grahasthee@gmail.com">grahasthee@gmail.com</a></p>'
),
(
  'refund-policy',
  'Refund & Return Policy',
  '<p>At Grahasthee, we value our customers and aim to provide a hassle-free experience for returns and refunds. Our policy is designed to be fair and transparent.</p><h5 class="mt-4 fw-bold text-uppercase">Return Eligibility</h5><p>You can initiate a return request within 7 days of delivery for most products. To be eligible for a return:</p><ul><li>The product must be unused, unwashed, and in the same condition as received.</li><li>Items must have original tags, packaging, and accessories included.</li><li>Stains, damage, or signs of usage will lead to rejection of the return.</li></ul><h5 class="mt-4 fw-bold text-uppercase">How to Initiate a Return</h5><p>To start a return, please contact us via:</p><ul><li>Email: <a href="mailto:grahasthee@gmail.com">grahasthee@gmail.com</a></li><li>WhatsApp: <a href="https://wa.me/917470652857">+917470652857</a></li></ul><p>Please provide your Order ID and photos of the product you wish to return.</p><h5 class="mt-4 fw-bold text-uppercase">Return Pick-up</h5><p>Once your return request is approved, our logistics partner will attempt a pick-up within 4 business days. The delivery personnel will perform a basic quality check at the doorstep.</p><h5 class="mt-4 fw-bold text-uppercase">Refund Process</h5><p>After the product reaches our warehouse and passes the quality inspection:</p><ul><li>For Prepaid orders: The refund will be credited back to the original payment method within 7-10 business days.</li><li>For COD orders: We will request your bank details or UPI ID to process the refund via bank transfer.</li></ul><h5 class="mt-4 fw-bold text-uppercase">Exchanges</h5><p>We offer one free replacement if the product delivered is damaged or incorrect. If you wish to exchange a product for other reasons (e.g., preference), additional shipping charges may apply.</p><h5 class="mt-4 fw-bold text-uppercase">Cancellations</h5><p>Cancellations are accepted within 4 hours of placing the order. Once the order is shipped, it cannot be canceled.</p><p class="mt-5 text-center text-muted">For any further questions, reach out to us at <a href="mailto:grahasthee@gmail.com">grahasthee@gmail.com</a></p>'
),
(
  'shipping-policy',
  'Shipping Policy',
  '<p>We ship across India. We also provide the COD option for Pin codes supported by our delivery partners.</p><p>Please refer to our shipping table below:</p><div class="table-responsive my-4"><table class="table table-bordered"><thead class="table-light"><tr><th>Orders</th><th>Delivery / COD charges</th></tr></thead><tbody><tr><td>All orders above Rs.799/-</td><td class="text-success fw-bold">Free</td></tr><tr><td>All orders below Rs.799/-</td><td>Rs.70/-</td></tr><tr><td>All COD orders</td><td>Rs.49/-</td></tr></tbody></table></div><p class="text-muted small">Please Note - this is subject to change as per Company policy.</p><h5 class="mt-4 fw-bold text-uppercase">Shipping Timeline</h5><p>Packages will be shipped in 48 working hours. We are closed on Sundays and will reach you in the next 5-7 days post shipping.</p><p>We give the estimated time of delivery on the shipping page. However, these are indicative and depend on our shipping partner.</p><h5 class="mt-4 fw-bold text-uppercase">Tracking & Delivery</h5><p>The delivery times are subject to location, distance, and our logistics partners. We are not liable for any delays in delivery by the courier company/postal authorities but will help you track down a package through our partner courier services.</p><p>Your purchases may reach you from various locations in more than one package. But rest assured, you will be charged one delivery fee for the entire order.</p><p>As soon as your package ships, we will email you your package tracking information.</p><h5 class="mt-4 fw-bold text-uppercase">Cash on Delivery (COD)</h5><p>Cash on Delivery is only available on orders above Rs.799 and lower than Rs.5000. The cash On Delivery option is not a trial option and payment is necessary before accepting the order. Any refusal of COD orders will result in the deactivation of the COD option for future orders.</p><p>In some pin codes, our shipping partners do not support COD and hence the option might be unavailable. For any queries, please contact our customer WhatsApp helpline.</p><h5 class="mt-4 fw-bold text-uppercase">Cancellations</h5><p>For any cancellations, we require an email within 4 hours of the order being placed. If the order is shipped out, cancellations will not be accepted. We will be unable to process any refund if an order is canceled at the doorstep or if there have been 3 failed attempts to deliver the parcel by our delivery partner.</p><h5 class="mt-4 fw-bold text-uppercase">International Shipping</h5><p>We currently do not ship outside India.</p><p class="mt-5">In case of any queries and doubts, please write to us at <a href="mailto:grahasthee@gmail.com">grahasthee@gmail.com</a></p>'
)
ON CONFLICT (slug) DO UPDATE
SET
  title = EXCLUDED.title,
  content = EXCLUDED.content;
